# Generated by Django 3.1.1 on 2020-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20200916_0743'),
    ]
    sql_query = '''create view voting_results as select lvv.id, lvv.date,
       (
            select max(vote_count) from (
                select count(lv.id) as vote_count
                    from lunch_voting
                        join lunch_vote lv on lunch_voting.id = lv.voting_id
                        join lunch_proposal lp on lp.id = lv.proposal_id
                where lunch_voting.id = lvv.id
                group by lunch_voting.id, restaurant_id) as tt
       ) as count_vote,

       (
            select restaurant_id from (
                select restaurant_id, count(lv.id) as vote_count
                    from lunch_voting
                        join lunch_vote lv on lunch_voting.id = lv.voting_id
                        join lunch_proposal lp on lp.id = lv.proposal_id
                where lunch_voting.id = lvv.id
                group by lunch_voting.id, restaurant_id) as tt order by vote_count desc limit 1
       ) as restaurant_id
       from lunch_voting as lvv order by lvv.date desc;
'''
    operations = [
        migrations.RunSQL(sql=sql_query, reverse_sql='DROP VIEW voting_results'),
    ]
